Organizations:
  - &OrdererOrg
    Name: Orderer
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/certification-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
    OrdererEndpoints:
      - orderer.certification-network.com:7050

  - &iit
    Name: iitMSP
    ID: iitMSP
    MSPDir: crypto-config/peerOrganizations/iit.certification-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('iitMSP.admin', 'iitMSP.peer', 'iitMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('iitMSP.admin', 'iitMSP.peer', 'iitMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('iitMSP.admin', 'iitMSP.peer', 'iitMSP.client')"
      Endorsement:
        Type: Signature
        Rule: "OR('iitMSP.admin', 'iitMSP.peer', 'iitMSP.client')"
    AnchorPeers:
      - Host: peer0.iit.certification-network.com
        Port: 7051

  - &mhrd
    Name: mhrdMSP
    ID: mhrdMSP
    MSPDir: crypto-config/peerOrganizations/mhrd.certification-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('mhrdMSP.admin', 'mhrdMSP.peer', 'mhrdMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('mhrdMSP.admin', 'mhrdMSP.peer', 'mhrdMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('mhrdMSP.admin', 'mhrdMSP.peer', 'mhrdMSP.client')"
      Endorsement:
        Type: Signature
        Rule: "OR('mhrdMSP.admin', 'mhrdMSP.peer', 'mhrdMSP.client')"
    AnchorPeers:
      - Host: peer0.mhrd.certification-network.com
        Port: 9051

  - &upgrad
    Name: upgradMSP
    ID: upgradMSP
    MSPDir: crypto-config/peerOrganizations/upgrad.certification-network.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('upgradMSP.admin', 'upgradMSP.peer', 'upgradMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('upgradMSP.admin', 'upgradMSP.peer', 'upgradMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('upgradMSP.admin', 'upgradMSP.peer', 'upgradMSP.client')"
      Endorsement:
        Type: Signature
        Rule: "OR('upgradMSP.admin', 'upgradMSP.peer', 'upgradMSP.client')"
    AnchorPeers:
      - Host: peer0.upgrad.certification-network.com
        Port: 11051



#Capabilities

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

#Application

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

#Orderer
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.certification-network.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities


#Profiles
Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *OrdererOrg
    Consortiums:
      CertificationConsortium:
        Organizations:
          - *iit
          - *mhrd
          - *upgrad

  CertificationChannel:
    Consortium: CertificationConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *iit
        - *mhrd
        - *upgrad
      Capabilities:
        <<: *ApplicationCapabilities
