version: '2'

volumes:
  orderer.certification-network.com:
  peer0.iit.certification-network.com:
  peer1.iit.certification-network.com:
  peer0.mhrd.certification-network.com:
  peer1.mhrd.certification-network.com:
  peer0.upgrad.certification-network.com:
  peer1.upgrad.certification-network.com:

networks:
  certification:

services:

  ca.iit.certification-network.com:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.iit.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.iit.certification-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/IIT_CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.iit.certification-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/IIT_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/iit.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.iit.certification-network.com
    networks:
      - certification

  ca.mhrd.certification-network.com:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.mhrd.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mhrd.certification-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/MHRD_CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.mhrd.certification-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/MHRD_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/mhrd.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.mhrd.certification-network.com
    networks:
      - certification

  ca.upgrad.certification-network.com:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.upgrad.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.upgrad.certification-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/UPGRAD_CA_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.upgrad.certification-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/UPGRAD_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/upgrad.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.upgrad.certification-network.com
    networks:
      - certification

  orderer.certification-network.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.certification-network.com
    container_name: orderer.certification-network.com
    networks:
      - certification

  couchdb.iit.peer0:
    container_name: couchdb.iit.peer0
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - certification

  couchdb.iit.peer1:
    container_name: couchdb.iit.peer1
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "6984:5984"
    networks:
      - certification

  couchdb.mhrd.peer0:
    container_name: couchdb.mhrd.peer0
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - certification

  couchdb.mhrd.peer1:
    container_name: couchdb.mhrd.peer1
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    networks:
      - certification

  couchdb.upgrad.peer0:
    container_name: couchdb.upgrad.peer0
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"
    networks:
      - certification

  couchdb.upgrad.peer1:
    container_name: couchdb.upgrad.peer1
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "10984:5984"
    networks:
      - certification

  peer0.iit.certification-network.com:
    container_name: peer0.iit.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.iit.certification-network.com
    networks:
      - certification
    depends_on:
      - couchdb.iit.peer0

  peer1.iit.certification-network.com:
    container_name: peer1.iit.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.iit.certification-network.com
    networks:
      - certification
    depends_on:
      - couchdb.iit.peer1

  peer0.mhrd.certification-network.com:
    container_name: peer0.mhrd.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.mhrd.certification-network.com
    networks:
      - certification
    depends_on:
      - couchdb.mhrd.peer0

  peer1.mhrd.certification-network.com:
    container_name: peer1.mhrd.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.mhrd.certification-network.com
    networks:
      - certification
    depends_on:
      - couchdb.mhrd.peer1

  peer0.upgrad.certification-network.com:
    container_name: peer0.upgrad.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.upgrad.certification-network.com
    networks:
      - certification
    depends_on:
      - couchdb.upgrad.peer0

  peer1.upgrad.certification-network.com:
    container_name: peer1.upgrad.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.upgrad.certification-network.com
    networks:
      - certification
    depends_on:
      - couchdb.upgrad.peer1

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGETAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.iit.certification-network.com:7051
      - CORE_PEER_LOCALMSPID=iitMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
      - ./../chaincode-advanced/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-advanced/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.iit.certification-network.com
      - ca.mhrd.certification-network.com
      - ca.upgrad.certification-network.com
      - orderer.certification-network.com
      - couchdb.iit.peer0
      - couchdb.iit.peer1
      - couchdb.mhrd.peer0
      - couchdb.mhrd.peer1
      - couchdb.upgrad.peer0
      - couchdb.upgrad.peer1
      - peer0.iit.certification-network.com
      - peer1.iit.certification-network.com
      - peer0.mhrd.certification-network.com
      - peer1.mhrd.certification-network.com
      - peer0.upgrad.certification-network.com
      - peer1.upgrad.certification-network.com
    networks:
      - certification

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:latest
    tty: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.iit.certification-network.com:7051
      - CORE_PEER_LOCALMSPID=iitMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
      - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - certification

